# Generated by Django 6.0.2 on 2026-02-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=15)),
                ('leverage', models.IntegerField(default=8)),
                ('margin_type', models.CharField(default='isolated', max_length=10)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('remaining_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('margin_used', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('current_stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('current_tp', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Entry'), ('open', 'Open'), ('partially_closed', 'Partially Closed'), ('closed', 'Closed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='signals.signal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbank_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('side', models.CharField(choices=[('open_long', 'Open Long'), ('open_short', 'Open Short'), ('close_long', 'Close Long'), ('close_short', 'Close Short')], max_length=15)),
                ('order_type', models.CharField(default='limit', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.position')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
