# Generated by Django 6.0.2 on 2026-02-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_msg_id', models.BigIntegerField(unique=True)),
                ('telegram_channel_id', models.BigIntegerField()),
                ('raw_text', models.TextField(blank=True, default='')),
                ('raw_image_path', models.CharField(blank=True, default='', max_length=500)),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('entry_price_low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price_high', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tp1', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('tp2', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('tp3', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('risk_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('leverage', models.IntegerField(default=8)),
                ('margin_type', models.CharField(default='isolated', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('partially_closed', 'Partially Closed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='new', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_msg_id', models.BigIntegerField(unique=True)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('update_type', models.CharField(choices=[('entry_hit', 'Entry Hit'), ('tp_hit', 'Take Profit Hit'), ('sl_modified', 'Stop Loss Modified'), ('partial_close', 'Partial Close'), ('full_close', 'Full Close'), ('risk_free', 'Risk Free (Move SL to Entry)'), ('position_closed', 'Position Fully Closed'), ('info', 'Informational')], max_length=20)),
                ('tp_number', models.IntegerField(blank=True, null=True)),
                ('new_stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('close_percentage', models.IntegerField(blank=True, null=True)),
                ('profit_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='signals.signal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
